
name: Deploy to Firebase

on: push

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
       - name: Setting
         run: |
               npm install
               npm install -g firebase-tools
       - name: Deploy
         run: |
               firebase deploy --token $FIREBASETOKEN
         env:
               FIREBASETOKEN: ${{ secrets.FIREBASETOKEN }}
